# Cloud Build 자동 배포 설정
# GitHub 연동 시 자동으로 빌드 및 배포

steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/lotto-predictor:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/lotto-predictor:latest'
      - '.'

  # 2. Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/lotto-predictor:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/lotto-predictor:latest'

  # 3. Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'lotto-predictor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lotto-predictor:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/lotto-predictor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/lotto-predictor:latest'

options:
  logging: CLOUD_LOGGING_ONLY
